### ISSUE TITLE
Home page: Section title and H2 of the section content are of the same size.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Arcus-Australia#30]
Applicable to Services and Talk to one of our experts today section.
![image](https://cloud.githubusercontent.com/assets/11186313/7508144/9a03d338-f4ad-11e4-957e-185303cc71a4.png)

**Comment by rexcebudigital** [comment]
Both of them is h2, only 1 h1 per page. homepage h1 is Who We Are title.

**Comment by roseliesromeo** [comment]
They are not part of the home page content.  They are H1 of Rentals and Service page. 
Also, H2 cannot be bigger than H1.
