### ISSUE TITLE
Products single page: Top of the images are faded.  Layout of the is different from the design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Arcus-Australia#47]
![image](https://cloud.githubusercontent.com/assets/11186313/7512042/810caace-f4dc-11e4-95ec-fa7539467fe6.png)

**Comment by rexcebudigital** [comment]
That gradient effect is an effect of the image. There's no issue on it if we change the image. :)

**Comment by doylesee** [comment]
This is a bug, next time do not input incorrect images.
