### ISSUE TITLE
Header section: Hover/active state background doesn't exactly fit the menu bar.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Arcus-Australia#56]
![image](https://cloud.githubusercontent.com/assets/11186313/7513280/84e0fad4-f4e5-11e4-96e7-854637408215.png)

**Comment by rexcebudigital** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/11186391/7647830/b9b01776-fb0d-11e4-8370-01e220cb7273.png)

**Comment by roseliesromeo** [comment]
Could have been affected by other fixes.
Will verify again once bug #98 is fixed.
