### ISSUE TITLE
Contact us page: Bottom of the input text is clipped.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Arcus-Australia#57]
![image](https://cloud.githubusercontent.com/assets/11186313/7513315/d79be54a-f4e5-11e4-8833-b22babf59232.png)

**Comment by rexcebudigital** [comment]
![contact arcus australia](https://cloud.githubusercontent.com/assets/11186391/7647774/060d3bb8-fb0d-11e4-91a4-9d1f8a8c74ae.png)

**Comment by roseliesromeo** [comment]
Not fixed in IE9.  This time top of the text is clipped.
![image](https://cloud.githubusercontent.com/assets/11186313/7742986/7d4b984a-ffc8-11e4-9151-3f4c130c94be.png)
