### ISSUE TITLE
Projects single page: Distorted layout of the image gallery.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Arcus-Australia#80]
![image](https://cloud.githubusercontent.com/assets/11186313/7558825/5945c934-f7df-11e4-891f-59eacb4d0e76.png)

**Comment by rexcebudigital** [comment]
The bug occurs because you haven't uploaded new pictures, instead you used uploaded pictures. I solved the bug by regenerating the thumbnails on media.

**Comment by roseliesromeo** [comment]
QAs normally upload only one image (large) for testing.  We use the images uploaded in the lib.
